[package]
name = "livetex"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
hyper = "1.5.2"
clap = { version = "4.5.26", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.6"